Bug#37256912 Add cmake support for using Homebrew clang
The Homebrew package manager will often release new software very
early. This also applies to clang, which is currently at version
19. Add support for using Homebrew clang, rather than Xcode on
mac. This will allow us to catch bugs in our code earlier.

Also fix:
router/src/router/src/uri.cc:54:19: error: unused variable 'kGenDelims' [-Werror,-Wunused-const-variable]

Change-Id: I28110a09bfea754d4f0360ec43e805a60adce982
(cherry picked from commit 5a35589758df2edd57075b62e80501684eb967ca)