Bug#37014761: Compile MySQL with clang 19 [noclose]
Fix errors of this type:

libs/mysql/serialization/archive.h:84:43: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
   84 |     return Archive_derived_type::template get_size(std::forward<Type>(arg));
      |                                           ^

Change-Id: Ic59bdf59fa5a0b8c11b664363a46101e2568e85c
(cherry picked from commit ec942c0737e9d41e80c181674ca0f71fedeff0f3)