Bug#37314959 Build with the LLVM standard library
error: use of undeclared identifier 'sprintf';
Add missing #include <stdio.h>

Change-Id: Icab0301ddb1cb0377a2049f1e2b89e9ea6486a17