Bug#37299071 ha_ndbcluster missing index handling escape
Post-push fix: on several platforms, in RelWithDebInfo builds
storage/ndb/plugin/ha_ndbcluster_push.cc:2496: undefined reference to `fail_index_offline(TABLE*, int)'

Change-Id: Ib94dc4e89bab80f2aca434543403c5a301676b48